### ISSUE TITLE
Make production ready

### ISSUE THREAD

**Issue by LoremFooBar** [cri5ti/AspNetCoreThrottler#1]
Hey 🙂 I found this project while looking for throttling in ASP.NET Core. I like the implementation and how lightweight this is, so I'm considering using it in a production project. I would be happy to help get this production ready!

For me to use it in a production project I will need the following implemented:

1. Tests
2. Custom partitioning
3. Better documentation

Let me know what you think and how you'd like to proceed and communicate.

**Comment by cri5ti** [comment]
Thank you for the project appreciation @lazyboy1, 
I have created individual issues from the points you raised: #2, #3, #4.
